### ISSUE TITLE
 Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by jersobh** [fidellr/jitsi-meet-wrapper#1]
index.js?4771:60 Uncaught TypeError: Cannot read property 'config' of undefined
    at new JitsiMeetConference (index.js?4771:60)
    at JitsiMeet.join (index.js?4771:44)
    at JitsiMeet.eval (Conference.vue?d244:127)
    at JitsiMeet.EventEmitter.emit (events.js?bf30:78)
    at err (index.js?4771:31)
    at HTMLScriptElement.script.onload (index.js?bacd:14)

**Comment by jersobh** [comment]
class JitsiMeetConference extends EventEmitter {
    constructor(baseUrl, room, selector, options) {
        super();

        this._roomUrl = `${baseUrl.href}${room}`;

        this._node = typeof selector === 'string'
            ? document.querySelector(selector)
            : selector;

        // XXX Fixup config overrides
        const config = Object.assign({}, options.config);

**Comment by fidellr** [comment]
Can u tell me specifically tht causing ur issue? I don't have a clue why did u get tht config of undefined

**Comment by fidellr** [comment]
as we already discussed it on google hangouts and its already been solved, i will close this issue
