### ISSUE TITLE
 api.executeCommand is not a function

### ISSUE THREAD

**Issue by jersobh** [fidellr/jitsi-meet-wrapper#2]
Seems that I cannot executeCommand, I get this error:  api.executeCommand is not a function

My code:

const JitsiMeet = require('jitsi-meet-wrapper')

const api = new JitsiMeet('https://live.mydomain.com/', options);
api.on('ready', () => {
    const conference = api.join('Test1234', element, initOptions);
    conference.on('joined', () => {
        api.executeCommand('displayName', 'New Nickname');
    })
})

**Comment by fidellr** [comment]
@jersobh check this solution https://github.com/jitsi/jitsi-meet/issues/1646, and let me know if it solved ur issue, going to close this and u could reopen if it still not working

**Comment by jersobh** [comment]
Still showing that error:
conference.vue?15d4:145 Uncaught TypeError: api.executeCommand is not a function
    at JitsiMeetConference.eval (conference.vue?15d4:145)
    at JitsiMeetConference.EventEmitter.emit (events.js?bf30:78)
    at JitsiMeetConference._onVideoConferenceJoined (index.js?4771:184)
    at JitsiMeetExternalAPI.<anonymous> (external_api.js:314)
    at listener (index.js:24)

**Comment by fidellr** [comment]
@jersobh can you make a gist or repo for that, so i could review your code

**Comment by jersobh** [comment]
https://gist.github.com/jersobh/64ffe19c8b092723825689775ed64616
